name: instprint
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+3


environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  google_fonts: ^4.0.4
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  file_selector: ^1.0.4
  syncfusion_flutter_pdf: ^24.2.5
  provider: ^6.1.1
  uuid: ^4.4.0
  pdf: ^3.10.4
  printing: ^5.12.0
  lottie: ^2.2.0
  shared_preferences: ^2.0.15
  image: ^4.1.0
  photo_view: ^0.14.0
  path_provider: ^2.0.14
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.14.4
  razorpay_flutter: ^1.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/lottie/login_printer.json
    - assets/lottie/success_tick.json
    - assets/logo.png

# ✅ Splash Screen Configuration
flutter_native_splash:
  color: "#FFC107" # Amber background
  image: assets/logo.png
  android: true
  ios: true
  web: false
  fullscreen: true

# ✅ App Icon Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

dependency_overrides:
  image: ^4.1.0
  fluttertoast: ^9.0.0

